### ISSUE TITLE
generated cpp 511 & Qt WebKit

### ISSUE THREAD

**Issue by nim65s** [MeVisLab/pythonqt#100]
Hi,

On ubuntu 20.04, with the `libqt5webkit5-dev` package installed, I get the following build error:
```
/usr/bin/ld: PythonQt_QtAll.o: in function `PythonQt_QtAll::init()':
PythonQt_QtAll.cpp:(.text+0x2e): undefined reference to `PythonQt_init_QtWebKit(_object*)'
```

It looks like the `com_trolltech_qt_webkit` directory is available in all `generated_cpp_5*` except `511`.

Uninstalling `libqt5webkit5-dev` workaround the issue.

Is this intentional, and should we avoid building webkit with 511, or was this directory forgotten at some point ?

**Comment by he-hesce** [comment]
If you want to use QtWebKit after it was officially dropped in Qt 5.6 (we still do) but still supplied by OS vendors, I recommend you edit libsrc/PythonQt/build/common.prf and comment out the use of the 5.11 wrappers. PythonQt will then fallback on the 5.6 wrappers which contains QtWebKit stuff though of course you will be limited to Qt 5.6 API in general which may or may not be okay depending on if you need new features added to Qt after 5.6.

Ubuntu 20.04 has Qt 5.12, so comment out these three lines:

```
#      else:contains( QT_MINOR_VERSION, 12 ) {
#        PYTHONQT_GENERATED_PATH = $$PWD/../generated_cpp_511
#      }
```

Then your build will fallback to 5.6 wrappers.

Best would of course be if 5.11 wrappers (and later if ever added) would ship with the QtWebKit stuff as well as it is still maintained but not by the Qt company. The original developer still maintains QtWebKit separately at it still ships with major Linux OS vendors.

**Comment by nim65s** [comment]
Thanks for your answer !

I'm sorry, but I don't remember exactly how I got there, so I'm not able to confirm if this solve my use case.

Let's say it does, I'll re-open if needed :)
