### ISSUE TITLE
Fails to build on some Arch systems. 

### ISSUE THREAD

**Issue by Zerophase** [MeVisLab/pythonqt#101]
Builds fine in a clean chroot. However, some systems get a ton of undefined references when building. More info on the issue can be found [In the aur](https://aur.archlinux.org/packages/pythonqt).

I tried using the default build and make settings, and disabling ccache with no success.

**Comment by mrbean-bremen** [comment]
Judging by the comments in the linked thread, this is a problem with the build environment that only happens for some people.
As we don't build on arch systems ourselves, there is nothing we can contribute here - I'm going to close this one...
