### ISSUE TITLE
Is this the latest version of PythonQt? What versions of Qt are supported? Anything past 5.5?

### ISSUE THREAD

**Issue by bhagerty** [MeVisLab/pythonqt#17]
First, this looks to be the main living fork of PythonQt. Is that right? 

Second, what versions of Qt are supported by this fork? Anything past 5.5? I ask because of this comment over in [build instructions for CsoundQt](https://github.com/CsoundQt/CsoundQt/blob/master/BUILDING.md): "NB! A word about Qt versions: PythonQt does not support Qt 5.6 yet. If you want to build with PythonQt support, use Qt 5.5.1 on Linux and Windows, Qt 5.4.2 on OSX (5.5 has a bug for OSX that does not let resize floating panels (like widgets' panel))."

I'm wondering if it is still true that PythonQt only works with Qt 5.5 (which is, I think, 5 years old).

**Comment by pieper** [comment]
Yes, I believe this is the official repo for PythonQt.

Not sure about CsoundQt, but for [Slicer](https://github.com/Slicer/Slicer) we use PythonQt with many Qt versions, including 5.15.

**Comment by bhagerty** [comment]
Thanks for the prompt response! I'll pursue this over at CsoundQt.

**Comment by florianlink** [comment]
Yes, this is the official repo, we moved from SourceForge a while ago.

Currently the newest pregenerated wrappers are for Qt 5.11 but they work for later Qt releases.
