### ISSUE TITLE
Is it possible to import installed modules

### ISSUE THREAD

**Issue by githubuser0xFFFF** [MeVisLab/pythonqt#19]
Hi,

First I would like to say thank you for this really nice open source project.

I would like to use external modules from PythonQt. For testing I just installed `pyreadline` via pip. If I open the python console, then I can enter `import pyreadline` to import the module. If I enter this import statement into the python cosole in the example applications, then I get the error:

```
py> import pyreadline
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pyreadline'
```

Is it possible to use external modules in PythonQt? Is there something tho consider that I missed?

Thank you,

Uwe

**Comment by githubuser0xFFFF** [comment]
Ok, I managed to solve this issue by adding the following line to the example:

```c++
PythonQt::self()->addSysPath("C:/Python38/Lib/site-packages");
```

**Comment by florianlink** [comment]
There is a flag on PythinQt::init() that enables site packages, you should
use that flag instead because site packages can also contain special config
files that only this mode will load correctly (via site.py)

**Comment by githubuser0xFFFF** [comment]
Ahh, I see. Sorry - I missed this. Thank you very much for your help.
