### ISSUE TITLE
[Solved] Cannot parse file: ':/trolltech/generator/build_all.txt'

### ISSUE THREAD

**Issue by huskier** [MeVisLab/pythonqt#202]
**[Solved] The current master source code has some problem, and we have to get the 3.5.0 branch to compile successfully.**

We've compiled PythonQt on Windows 11 platform, and the related information as following:
Python: 3.11 (Anaconda Python distribution)
Qt: 5.15.2 LTS
Compiler tools: MSVC2019 (x64)

It seems that PythonQt is successfully compiled and linked. However, We still get the following error. We have no idea about the error. Any ideas about the error?

> 12:56:52: Starting D:\development\github_gitlib\build-PythonQt-Desktop_Qt_5_15_2_MSVC2019_64bit-Release\generator\release\pythonqt_generator.exe...
> ghijt LoadLibrary(C:\Program Files (x86)\Qianxin\Tianqing\hookbase\x64\VCOMP140.DLL) success
> Please wait while source files are being generated...
> Trying to determine Qt version...
> 
> Using QT at: C:\Application\Qt\5.15.2\msvc2019_64
> 
> Determined Qt version is 5.15.2
> Parsing typesystem file [:/trolltech/generator/build_all.txt]
> **Fatal error: line=1, column=1, message=unexpected end of file**
> 
> **Fatal error: line=2, column=62, message=Failed to parse: 'typesystem_core.xml'**
> 
> **Cannot parse file: ':/trolltech/generator/build_all.txt'**
> 12:56:56: D:\development\github_gitlib\build-PythonQt-Desktop_Qt_5_15_2_MSVC2019_64bit-Release\generator\release\pythonqt_generator.exe crashed.

**Comment by huskier** [comment]
I don't know how to solve the issue directly, but I could workaround it through switching to 3.5.0 source code.

**Comment by mrbean-bremen** [comment]
Ok, so your problem was with the current master? In this case it could be a regression...

**Comment by huskier** [comment]
Maybe. Maybe it need more people to test this issue.

**Comment by mrbean-bremen** [comment]
So, did I understand you correctly, that the problem happenend with the current master, but not with the 3.5.0 release sources? Or did you use another version before?

**Comment by huskier** [comment]
Yes, you are right. There is no problem for 3.5.0 release source. The problem happend on the current master source.

**Comment by mrbean-bremen** [comment]
Closing as not reproducible. Feel free to reopen if you can reproduce the problem.
