### ISSUE TITLE
Qt 6.7: Several bindings are not generated

### ISSUE THREAD

**Issue by mrbean-bremen** [MeVisLab/pythonqt#224]
We noticed this only after making the patch release. 
Qt 6.7 binding are still quite incomplete, missing wrappers for QtCore include:
- QDeferredDeleteEvent
- QStandardPaths
- QStorageInfo
- QSystemSemaphore
- QTemporaryDir
- QTemporaryFile
- QTimeLine
- QTimer
- QTranslator
- QUrlQuery
- QWaitCondition
- QStreamEntityResolver

Also missing are operators for QDateTime and QTime.

**Comment by usiems** [comment]
Should be fixed with merge request #225.
