### ISSUE TITLE
Issue compiling on Arch Linux with python 3.13

### ISSUE THREAD

**Issue by FabioLolix** [MeVisLab/pythonqt#245]
Hi, I'm the AUR maintainer of [pythonqt-git](https://aur.archlinux.org/packages/pythonqt-git) on AUR, with the update to Python 3.13.1 in the Arch Linux repository I have tried to rebuild the program, there is this issue; the same is happening for the last stable version 3.5.6

```
PythonQt.cpp: In constructor 'PythonQt::PythonQt(int, const QByteArray&)':
PythonQt.cpp:352:8: error: 'PyEval_ThreadsInitialized' was not declared in this scope; did you mean 'PythonAlreadyInitialized'?
  352 |   if (!PyEval_ThreadsInitialized()) {
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~
      |        PythonAlreadyInitialized
```

**Comment by mrbean-bremen** [comment]
Thanks! A bit of googling shows that this has indeed been removed.

From the Python 3.13 release notes:
> Remove the PyEval_ThreadsInitialized() function, deprecated in Python 3.9. Since Python 3.7, Py_Initialize() always creates the GIL: calling PyEval_InitThreads() does nothing and PyEval_ThreadsInitialized() always returns non-zero.

So this check can savely be removed from the code.

**Comment by FabioLolix** [comment]
OK, I have removed the whole

```
#ifdef PYTHONQT_FULL_THREAD_SUPPORT
  if (!PyEval_ThreadsInitialized()) {
    PyEval_InitThreads();
  }
#endif
```

and builded again, can I make the PR?

**Comment by mrbean-bremen** [comment]
Of course, go ahead!

**Comment by mrbean-bremen** [comment]
Maybe it also makes sense to add a Python 3.13 build to the CI - the OS does not really matter.

**Comment by mrbean-bremen** [comment]
@FabioLolix - do you need a patch release?

**Comment by FabioLolix** [comment]
[pythonqt-git](https://aur.archlinux.org/packages/pythonqt-git) doesn't really need it because it pull the latest commit at build time but I'm sure other packagers will appreciate

**Comment by mrbean-bremen** [comment]
Ok, thanks!
