### ISSUE TITLE
when Qt5 build: error: /bigobj: No such file or directory

### ISSUE THREAD

**Issue by fuchengjie** [MeVisLab/pythonqt#29]
as title
![image](https://user-images.githubusercontent.com/31361595/98333217-350aed80-203b-11eb-9026-a6cf6fc74695.png)

i used QT5.12 on Windows 64.
And i used QT5.9.9 , failed again.

**Comment by usiems** [comment]
I guess you didn't compile with Visual Studio? If you use mingw, try again, I have just merged some contributed fixes for MinGW build.

**Comment by fuchengjie** [comment]
Thank for you attention😀.
I have fixed it by using Visual Studio2015. (In this photo i used QT creator)

**Comment by fuchengjie** [comment]
fixed
