### ISSUE TITLE
Failing to execute Example: No module named 'encodings'

### ISSUE THREAD

**Issue by Murmele** [MeVisLab/pythonqt#31]
I tried to use pythonqt and to execute one of the examples. I used a preinstalled python 3.8 version without debug symbols or anything else. In Debug mode I'm getting a linker error that a python3.8_d.dll library is missing (#4 Ensure PYTHONQT_USE_RELEASE_PYTHON_FALLBACK works as expected ). In Release mode I can build the library and start the application, but I get the error below. I compared the sys paths between here and when executing python in a console and there I see that the path to Python38\\Lib\\site-packages is missing. I don't know if it is the problem. 

Qt: 5.12.10, Mingw 7.3
Windows 10
Python 3.8
PythonQt commit: 9ea0fcf (latest commit on master)

Python path configuration:
  PYTHONHOME = 'C:\Qt\Tools\mingw730_64\bin\..\opt'
  PYTHONPATH = 'AppData\Local\Programs\Python\Python38'
  program name = 'PythonQtTest'
  isolated = 0
  environment = 1
  user site = 1
  import site = 0
  sys._base_executable = 'build-PythonQt-Desktop_Qt_5_12_10_MinGW_64_bit-Release\\lib\\PyScriptingConsole.exe'
  sys.base_prefix = 'C:\\Qt\\Tools\\mingw730_64\\bin\\..\\opt'
  sys.base_exec_prefix = 'C:\\Qt\\Tools\\mingw730_64\\bin\\..\\opt'
  sys.executable = 'build-PythonQt-Desktop_Qt_5_12_10_MinGW_64_bit-Release\\lib\\PyScriptingConsole.exe'
  sys.prefix = 'C:\\Qt\\Tools\\mingw730_64\\bin\\..\\opt'
  sys.exec_prefix = 'C:\\Qt\\Tools\\mingw730_64\\bin\\..\\opt'
  sys.path = [
    'AppData\\Local\\Programs\\Python\\Python38',
    'AppData\\Local\\Programs\\Python\\Python38\\python38.zip',
    'C:\\Qt\\Tools\\mingw730_64\\bin\\..\\opt\\DLLs',
    'C:\\Qt\\Tools\\mingw730_64\\bin\\..\\opt\\lib',
    build-PythonQt-Desktop_Qt_5_12_10_MinGW_64_bit-Release\\lib',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000114 (most recent call first):
<no Python frame>
Fatal Python error: 
failed to get the Python codec of the filesystem encoding

**Comment by Murmele** [comment]
Thank you.
I set PYTHONPATH to AppData\Local\Programs\Python\Python38 but it must be set to AppData\Local\Programs\Python\Python38\Lib

**Comment by GeoGroup** [comment]
> 

Have you fix this problem? I have the same problem in runing PythonQtTest
