### ISSUE TITLE
Alternatives to Qt from the Qt Company .... considering Copperspice

### ISSUE THREAD

**Issue by ShamanTcler** [MeVisLab/pythonqt#36]
With the Qt Companies recent business moves, I am considering Copperspice as a drop in replacement. 

https://www.copperspice.com

-  Copperspice is LGPL 2.1
-  Copperspice is somewhere around Qt 5.6 capability
-  C++ 17 compliant 

If I have to migrate to Qt 6 just might consider Copperspice as an alternative.

Thoughts?

**Comment by usiems** [comment]
I think this is not the right context to contemplate this question. We probably would accept reasonable patches to create Copperspice compatibility though, it they are not too invasive.
