### ISSUE TITLE
Feature request: add support for pathlib

### ISSUE THREAD

**Issue by fepegar** [MeVisLab/pythonqt#38]
Hi all,

Are there any plans to add support for [`pathlib.Path`](https://docs.python.org/3/library/pathlib.html) objects instead of strings only?

**Comment by usiems** [comment]
I'm a little bit unsure: What type of support would expect exactly?

**Comment by fepegar** [comment]
Hi, @usiems. Thanks for replying. This comes from my post on the [3D Slicer discourse](https://discourse.slicer.org/t/support-for-pathlib/9131).

I have no idea what would need to be changed in the library, maybe it's supported already and this issue is pointless.

The idea is just that `pathlib` is becoming more and more used, and other libraries have adapted their APIs so e.g. readers and writers take either strings or path-like objects. This is not a feature I necessarily need a lot, typically I just go `str(path_object)`, but I was wondering if this issue had been considered here.

**Comment by usiems** [comment]
Well, this works for me:
```
from PythonQt.QtCore import QFileInfo
from pathlib import Path
p = Path(r"C:\users\usiems")
fi = QFileInfo(p)
print(fi)
```
As long as a slot method expects a QString parameter, pathlib.Path (and anything else that can be converted to a string) should be auto-converted to QString.

**Comment by fepegar** [comment]
Thanks, I suppose that settles it! I'll reopen if new questions come up.
