### ISSUE TITLE
no quit() function available

### ISSUE THREAD

**Issue by tonka3000** [MeVisLab/pythonqt#4]
Hey,

I try to use the python builtin `quit()` function, but I always get not defined. Is there any possibility to activate that when python is embedded?

Greetings  
Tonka

**Comment by florianlink** [comment]
You can use

QtCore.QCoreApplication.quit()

or if you want to overwrite this, you could eval the following script before running the user code:

quit = QtCore.QCoreApplication.quit()

or somehow try to inject quit into the __builtins__ Python module before running user script.

**Comment by tonka3000** [comment]
Hey,

I‘ve defined `quit` before running user code with `sys.exit`, but also your answer is valid

```py
def quit():
    import sys
    sys.exit()
```

Thanks for your answer
