### ISSUE TITLE
Handling pythonqt deadblocking UI

### ISSUE THREAD

**Issue by FreBenRUB** [MeVisLab/pythonqt#46]
Hey there, im new to PythonQt. I've embedded a simple python scripting widget into my application to basically call c++ functions through a CPPClass that i've registered to PythonQt. It should be noted, that i am not manipulating the UI. Everything works as expected, as long as i don't execute any infinite loop or other deadlocking things. This results in a deadlock, freezing the entire application. I want to be able to stop the execution on the run.

I've tried initializing PythonQt and evaluating code in another QThread. Also i experimented with the setEnableThreadSupport setting and the information about releasing and restoring gil states i found in various threads here. No change of behaviour.

So at this point im stuck and just asking whether there is an obvious solution i just can't see.

Thank you for any answer

**Comment by Gehogor** [comment]
Hi, I met the same problem and I use this solution, for sure it is not the best idea. Maybe it will help you.
After the PhytonQt environment initialization in your thread call the following code to map a standard python callback :
```
PythonQtObjectPtr module = PythonQt::self()->getMainModule();
PyEval_SetProfile(traceHook,module.object());
```

And after add this code in the _traceHook_ callback (static method) :
```
if( g_executor->hasToStop() )
    {
        QString type;
        if( what == PyTrace_CALL ) type = "PyTrace_CALL";
        else if( what == PyTrace_EXCEPTION ) type = "PyTrace_EXCEPTION";
        else if( what == PyTrace_LINE ) type = "PyTrace_LINE";
        else if( what == PyTrace_RETURN ) type = "PyTrace_RETURN";
        else if( what == PyTrace_C_CALL ) type = "PyTrace_C_CALL";
        else if( what == PyTrace_C_EXCEPTION ) type = "PyTrace_C_EXCEPTION";
        else if( what == PyTrace_C_RETURN ) type = "PyTrace_C_RETURN";
        else if( what == PyTrace_OPCODE ) type = "PyTrace_OPCODE";

        PyErr_SetString( PyExc_Exception,
                         tr("Interruption of script at line [%1] [%2].")
                         .arg(PyFrame_GetLineNumber(frame))
                         .arg(type).toStdString().c_str() );
        return -1;
    }

    return 0;
```
The element _g_executor_ is a thread safe global variable that you can use to stop the script. If in your script you call a _sleep_ method, it won't work but it is normal. In this case you have to force to terminate the thread (easy to do with Qt).

**Comment by FreBenRUB** [comment]
Thanks for the quick answer. This type of tracing functions i didn't know. Now i've got the possibility to interrupt python calls on the run. Thank you!
Sadly my main problem, the UI blocking, still remains, so there is no chance to change the threadsafe variable and call the interruption.
I assume this is a basic threading problem i don't understand.

Does it matter where i start the QThread?

**Comment by Gehogor** [comment]
I think is not the right place to speak about thread, I'm not a discussion thread specialist. However maybe I can answer you quickly. You can start your thread where you want. The most important is to call the method _evalScript_ (or similar) in your thread. In this case, your main thread which is in charge of all widgets execution won't be 'blocked'.

**Comment by YuDe95** [comment]
> Hey there, im new to PythonQt. I've embedded a simple python scripting widget into my application to basically call c++ functions through a CPPClass that i've registered to PythonQt. It should be noted, that i am not manipulating the UI. Everything works as expected, as long as i don't execute any infinite loop or other deadlocking things. This results in a deadlock, freezing the entire application. I want to be able to stop the execution on the run.
> 
> I've tried initializing PythonQt and evaluating code in another QThread. Also i experimented with the setEnableThreadSupport setting and the information about releasing and restoring gil states i found in various threads here. No change of behaviour.
> 
> So at this point im stuck and just asking whether there is an obvious solution i just can't see.
> 
> Thank you for any answer

Have you solved the problem？

**Comment by YuDe95** [comment]
@FreBenRUB  Have you solved the problem

**Comment by FreBenRUB** [comment]
Hi sorry, i did not answer. I did solve it, by a simple thing i missed. I had to turn all Slot-Connections to Qt:BlockingQueuedConnections.
