### ISSUE TITLE
Add .isatty() to PythonQtStdIn

### ISSUE THREAD

**Issue by fepegar** [MeVisLab/pythonqt#48]
Hello. I would like an `isatty` method in `stdin` as the one in `stdout`:

https://github.com/MeVisLab/pythonqt/blob/58ccd5393922d88fd320628aa2db787df1f1233b/src/PythonQtStdOut.cpp#L115-L117

May I open a PR to add it to https://github.com/MeVisLab/pythonqt/blob/master/src/PythonQtStdIn.cpp? This is to follow the advice I was given at https://github.com/Slicer/Slicer/issues/5705 to fix an issue using `pip` within the 3D Slicer Python console.

**Comment by usiems** [comment]
Yes, of course, should be straightforward.

**Comment by fepegar** [comment]
Thanks!
