### ISSUE TITLE
error: \python27.lib: No such file or directory

### ISSUE THREAD

**Issue by hbtalha** [MeVisLab/pythonqt#53]
I am trying to build  pythonqt on windows Qt mingw 5.15.2 but I am getting this error.

`:-1: error: error: \python27.lib: No such file or directory`
`:-1: error: [Makefile.Release:179: ../lib/PythonQt-Qt5-Python27.dll] Error 1`

**Comment by skycuckoo** [comment]
Try to set the environment variables everywhere you see.
If you use QTCreator, try to restart this app after you set the enviroment variables.

**Comment by hantwain** [comment]
meet the same issue.

**Comment by HectorJiang** [comment]
> I am trying to build pythonqt on windows Qt mingw 5.15.2 but I am getting this error.
> 
> `:-1: error: error: \python27.lib: No such file or directory` `:-1: error: [Makefile.Release:179: ../lib/PythonQt-Qt5-Python27.dll] Error 1`

1.Confirm your python version and python installation folder, such as python3.8
2.You need to set your system environment variables:
set PYTHON_PATH=c:\Python38
set PYTHON_LIB=c:\Python38\libs
set PYTHON_VERSION=3.8

**Comment by mrbean-bremen** [comment]
Closing - outdated and missing response.
