### ISSUE TITLE
bind C++ function

### ISSUE THREAD

**Issue by kerim371** [MeVisLab/pythonqt#54]
Hi,

There are examples and tests demonstrating how to bind C++ class but is there a way to bind C++ function?
For example I have:
```Cpp
namespace ns{

bool foo(QString &str){ return true; }

}
```
How would look PythonQt code to bind this function in `ns` python package?

**Comment by Gehogor** [comment]
I think you already know but we never know, for my side I do like this. I create a binder class for method:
```
class YourPythonBinder
        : public QObject
{
    Q_OBJECT

public:
    YourPythonBinder();
    ~YourPythonBinder(){}

public slots:
    void log(const QString& key,const QString& msg)
    {
        printf("[%s]: %s\n",key.toSdtString().c_str(),msg.toSdtString().c_str());
    }

    void warn(const QString& key,const QString& msg);
    void err(const QString& key,const QString& msg);
};
```
After, somewhere in your code, you initialize the PythonQt environment:
```
{
    PythonQt::init( PythonQt::RedirectStdOut );
    PythonQt_QtAll::init();
    PythonQtObjectPtr module = PythonQt::self()->getMainModule();
    PythonQt::self()->addObject(module,"ns",new YourPythonBinder());
}
```

And, you can use you binder method as:
```
from PythonQt import *
ns.warn("KEY","Why not")
```

In additional, what I understood is that we cannot resolve namespace. In your c++ code (*.cpp or *.h), you have to resolve it before to declare any methods or objects. I don't know how to create independent Python module that you can use as an "import" library. I guess someone will explain how to do it.

**Comment by kerim371** [comment]
@Gehogor thank you very much!

I think I understood the idea and this should work. Now I'm trying to apply it to my special case
