### ISSUE TITLE
how to use pythran add a myfunction from other py files?

### ISSUE THREAD

**Issue by YuDe95** [MeVisLab/pythonqt#56]
#### toolsTep.py

```python
def HelloWord():
    print('hello word')
```

#### testpythran.py

```python
from calaTools.toolsTep import *
#pythran export callOtherPyFiles()
def callOtherPyFiles():
    HelloWord()
```

#### complie pythran testpythran.py

 - **CRITICAL** :  
   I am in trouble. Your input file does not seem to match Pythran's constraints...
 - testpythran.py:
   > None:None error: Module 'calaTools.toolsTep' not found.
#### when tow function in save file and it can find ,in diffrent file it occured those errors

**Comment by wangdaye078** [comment]
sys.path.append('.')
from toolsTep import *

**Comment by mrbean-bremen** [comment]
Not related to pythonqt, closing.
