### ISSUE TITLE
Need for a fresh tag

### ISSUE THREAD

**Issue by benbarate** [MeVisLab/pythonqt#58]
Hello,

We are currently working on integrating pythonqt in our Simcenter System Architect product which is a Qt based application. This integration will allow us to pilot our GUI in order to create and execute integration tests.

We are currently relying on the master for our development however we will required a tag to comply to our Siemens OSS clearance process. There is currently no tag of python Qt and the last 3.2 branch is four years old which is too bad.

Is-it possible to create a fresh tag?

**Comment by benbarate** [comment]
Seems related to #12.

**Comment by mrbean-bremen** [comment]
Fixed with #12.
