### ISSUE TITLE
Build broken after python update to 3.8

### ISSUE THREAD

**Issue by jghodd** [MeVisLab/pythonqt#6]
After updating python from 3.7 to 3.8, a re-build of libPythonQt_QtAll-Qt5-Python3.so.3.2.0 is still trying to resolve libpython3.7m.so.1.0 which, of course, no longer exists.

# ldd libPythonQt_QtAll-Qt5-Python3.so.3.2.0
        linux-vdso.so.1 (0x00007ffe340b2000)
        libPythonQt-Qt5-Python3.so.3 => /usr/lib/libPythonQt-Qt5-Python3.so.3 (0x00007f570fbd9000)
        libQt5Svg.so.5 => /usr/lib/libQt5Svg.so.5 (0x00007f570fb80000)
        libQt5OpenGL.so.5 => /usr/lib/libQt5OpenGL.so.5 (0x00007f570fb27000)
        libQt5PrintSupport.so.5 => /usr/lib/libQt5PrintSupport.so.5 (0x00007f570fab2000)
        libQt5MultimediaWidgets.so.5 => /usr/lib/libQt5MultimediaWidgets.so.5 (0x00007f570fa92000)
        libQt5QuickWidgets.so.5 => /usr/lib/libQt5QuickWidgets.so.5 (0x00007f570fa7c000)
        libQt5WebKitWidgets.so.5 => /usr/lib/libQt5WebKitWidgets.so.5 (0x00007f570fa2e000)
        libQt5Widgets.so.5 => /usr/lib/libQt5Widgets.so.5 (0x00007f570f396000)
        libQt5Multimedia.so.5 => /usr/lib/libQt5Multimedia.so.5 (0x00007f570f280000)
        libQt5Quick.so.5 => /usr/lib/libQt5Quick.so.5 (0x00007f570edb2000)
        libQt5WebKit.so.5 => /usr/lib/libQt5WebKit.so.5 (0x00007f570bd43000)
        libQt5Gui.so.5 => /usr/lib/libQt5Gui.so.5 (0x00007f570b75f000)
        libQt5Sql.so.5 => /usr/lib/libQt5Sql.so.5 (0x00007f570b70f000)
        libQt5XmlPatterns.so.5 => /usr/lib/libQt5XmlPatterns.so.5 (0x00007f570b330000)
        libQt5Qml.so.5 => /usr/lib/libQt5Qml.so.5 (0x00007f570ae54000)
        libQt5Network.so.5 => /usr/lib/libQt5Network.so.5 (0x00007f570ac99000)
        libQt5Xml.so.5 => /usr/lib/libQt5Xml.so.5 (0x00007f570ac57000)
        libQt5Core.so.5 => /usr/lib/libQt5Core.so.5 (0x00007f570a74a000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f570a55e000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f570a544000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f570a37d000)
        **_libpython3.7m.so.1.0 => not found_**
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f570a237000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f570a21d000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f570a1f9000)
        libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f570a165000)
        libpulse.so.0 => /usr/lib/libpulse.so.0 (0x00007f570a110000)
        libQt5WebChannel.so.5 => /usr/lib/libQt5WebChannel.so.5 (0x00007f570a0ec000)
        libicuuc.so.65 => /usr/lib/libicuuc.so.65 (0x00007f5709f0a000)
        libQt5Positioning.so.5 => /usr/lib/libQt5Positioning.so.5 (0x00007f5709e72000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f5709d32000)
        libicui18n.so.65 => /usr/lib/libicui18n.so.65 (0x00007f5709a3e000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f5709a39000)
        libQt5Sensors.so.5 => /usr/lib/libQt5Sensors.so.5 (0x00007f57099f7000)
        libwoff2dec.so.1.0.2 => /usr/lib/libwoff2dec.so.1.0.2 (0x00007f57097ec000)
        libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x00007f5709753000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f570971b000)
        libwebp.so.7 => /usr/lib/libwebp.so.7 (0x00007f57096ab000)
        libhyphen.so.0 => /usr/lib/libhyphen.so.0 (0x00007f57094a5000)
        libxml2.so.2 => /usr/lib/libxml2.so.2 (0x00007f570933d000)
        libxslt.so.1 => /usr/lib/libxslt.so.1 (0x00007f57092fc000)
        libsqlite3.so.0 => /usr/lib/libsqlite3.so.0 (0x00007f57091ce000)
        libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x00007f570901e000)
        libgstapp-1.0.so.0 => /usr/lib/libgstapp-1.0.so.0 (0x00007f570900e000)
        libgstbase-1.0.so.0 => /usr/lib/libgstbase-1.0.so.0 (0x00007f5708f9e000)
        libgstreamer-1.0.so.0 => /usr/lib/libgstreamer-1.0.so.0 (0x00007f5708e90000)
        libgstpbutils-1.0.so.0 => /usr/lib/libgstpbutils-1.0.so.0 (0x00007f5708e5a000)
        libgstaudio-1.0.so.0 => /usr/lib/libgstaudio-1.0.so.0 (0x00007f5708de6000)
        libgsttag-1.0.so.0 => /usr/lib/libgsttag-1.0.so.0 (0x00007f5708dac000)
        libgstvideo-1.0.so.0 => /usr/lib/libgstvideo-1.0.so.0 (0x00007f5708d0b000)
        libgstfft-1.0.so.0 => /usr/lib/libgstfft-1.0.so.0 (0x00007f5708d01000)
        libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007f5708ca5000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f5708b80000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f5708b73000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f57112a3000)
        libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f5708a6f000)
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f57089df000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f570870e000)
        libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007f5708667000)
        libpcre2-16.so.0 => /usr/lib/libpcre2-16.so.0 (0x00007f57085e4000)
        libdouble-conversion.so.3 => /usr/lib/libdouble-conversion.so.3 (0x00007f57085cd000)
        libzstd.so.1 => /usr/lib/libzstd.so.1 (0x00007f5708525000)
        libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007f57084f1000)
        libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f57084dc000)
        libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007f570841c000)
        libpulsecommon-13.0.so => /usr/lib/pulseaudio/libpulsecommon-13.0.so (0x00007f5708398000)
        libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007f570834e000)
        libicudata.so.65 => /usr/lib/libicudata.so.65 (0x00007f570689d000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f5706873000)
        libwoff2common.so.1.0.2 => /usr/lib/libwoff2common.so.1.0.2 (0x00007f570666e000)
        libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x00007f5706660000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f5706638000)
        libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007f5706633000)
        libmount.so.1 => /usr/lib/libmount.so.1 (0x00007f57065d3000)
        libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f57065b8000)
        libunwind.so.8 => /usr/lib/libunwind.so.8 (0x00007f570659e000)
        libdw.so.1 => /usr/lib/libdw.so.1 (0x00007f570654a000)
        liborc-0.4.so.0 => /usr/lib/liborc-0.4.so.0 (0x00007f57064c8000)
        libffi.so.6 => /usr/lib/libffi.so.6 (0x00007f57064bd000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f5706448000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f570637a000)
        libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f5706355000)
        liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007f5706333000)
        libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007f5706215000)
        libsndfile.so.1 => /usr/lib/libsndfile.so.1 (0x00007f5706197000)
        libasyncns.so.0 => /usr/lib/libasyncns.so.0 (0x00007f570618f000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f570618a000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f5706182000)
        libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x00007f570615f000)
        libblkid.so.1 => /usr/lib/libblkid.so.1 (0x00007f5706107000)
        libelf.so.1 => /usr/lib/libelf.so.1 (0x00007f57060ed000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f57060da000)
        libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f57060b7000)
        libFLAC.so.8 => /usr/lib/libFLAC.so.8 (0x00007f5706078000)
        libogg.so.0 => /usr/lib/libogg.so.0 (0x00007f570606b000)
        libvorbis.so.0 => /usr/lib/libvorbis.so.0 (0x00007f5705e3f000)
        libvorbisenc.so.2 => /usr/lib/libvorbisenc.so.2 (0x00007f5705b96000)

What needs to be changed for a build against python-3.8?

**Comment by krop** [comment]
On openSUSE, we're seeing this (extract):

```
[  198s] g++ -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -Wl,-soname,libPythonQt-Qt5-Python3.so.3 -o libPythonQt-Qt5-Python3.so.3.2.0 PythonQtStdDecorators.o PythonQt.o PythonQtClassInfo.o PythonQtImporter.o PythonQtObjectPtr.o PythonQtProperty.o PythonQtStdIn.o PythonQtStdOut.o PythonQtSignal.o PythonQtSlot.o PythonQtSlotDecorator.o PythonQtMisc.o PythonQtMethodInfo.o PythonQtConversion.o PythonQtSignalReceiver.o PythonQtInstanceWrapper.o PythonQtQFileImporter.o PythonQtClassWrapper.o PythonQtBoolResult.o PythonQtScriptingConsole.o com_trolltech_qt_core_builtin0.o com_trolltech_qt_core_builtin_init.o com_trolltech_qt_gui_builtin0.o com_trolltech_qt_gui_builtin_init.o moc_PythonQt.o moc_PythonQtStdDecorators.o moc_PythonQtSignalReceiver.o moc_PythonQtScriptingConsole.o moc_com_trolltech_qt_core_builtin0.o moc_com_trolltech_qt_gui_builtin0.o  -lcrypt -ldl -lutil -lm /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Core.so -lGL -lpthread    
[  291s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /tmp/libPythonQt-Qt5-Python3.so.3.2.0.HHrIKK.ltrans2.ltrans.o: in function `_object* PythonQtConvertPairToPython<QString, QSizeF>(void const*, int)':
[  291s] /home/abuild/rpmbuild/BUILD/PythonQt3.2/src/PythonQtConversion.h:346: undefined reference to `PyTuple_New'
[  291s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /tmp/libPythonQt-Qt5-Python3.so.3.2.0.HHrIKK.ltrans2.ltrans.o: in function `_object* PythonQtConvertPairToPython<double, QVariant>(void const*, int)':
[  291s] /home/abuild/rpmbuild/BUILD/PythonQt3.2/src/PythonQtConversion.h:346: undefined reference to `PyTuple_New'
[  291s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /tmp/libPythonQt-Qt5-Python3.so.3.2.0.HHrIKK.ltrans2.ltrans.o: in function `_object* PythonQtConvertPairToPython<double, QPointF>(void const*, int)':
[  291s] /home/abuild/rpmbuild/BUILD/PythonQt3.2/src/PythonQtConversion.h:346: undefined reference to `PyTuple_New'
[  291s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /tmp/libPythonQt-Qt5-Python3.so.3.2.0.HHrIKK.ltrans2.ltrans.o: in function `_object* PythonQtConvertPairToPython<double, QColor>(void const*, int)':
[  291s] /home/abuild/rpmbuild/BUILD/PythonQt3.2/src/PythonQtConversion.h:346: undefined reference to `PyTuple_New'
[  291s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /tmp/libPythonQt-Qt5-Python3.so.3.2.0.HHrIKK.ltrans2.ltrans.o: in function `_object* PythonQtConvertPairToPython<QByteArray, QByteArray>(void const*, int)':
[  291s] /home/abuild/rpmbuild/BUILD/PythonQt3.2/src/PythonQtConversion.h:346: undefined reference to `PyTuple_New'
[  291s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /tmp/libPythonQt-Qt5-Python3.so.3.2.0.HHrIKK.ltrans2.ltrans.o:/home/abuild/rpmbuild/BUILD/PythonQt3.2/src/PythonQtConversion.h:346: more undefined references to `PyTuple_New' follow
[  291s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /tmp/libPythonQt-Qt5-Python3.so.3.2.0.HHrIKK.ltrans2.ltrans.o: in function `bool PythonQtConvertPythonToPair<double, double>(_object*, void*, int, bool)':
[  291s] /home/abuild/rpmbuild/BUILD/PythonQt3.2/src/PythonQtConversion.h:368: undefined reference to `PySequence_Check'
[  291s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/PythonQt3.2/src/PythonQtConversion.h:369: undefined reference to `PySequence_Size'
[  291s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/PythonQt3.2/src/PythonQtConversion.h:374: undefined reference to `PySequence_GetItem'
[  291s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /tmp/libPythonQt-Qt5-Python3.so.3.2.0.HHrIKK.ltrans2.ltrans.o: in function `bool PythonQtConvertPythonToPair<double, double>(_object*, void*, int, bool)':
[  291s] /usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
[  291s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /tmp/libPythonQt-Qt5-Python3.so.3.2.0.HHrIKK.ltrans2.ltrans.o: in function `bool PythonQtConvertPythonToPair<double, double>(_object*, void*, int, bool)':
[  291s] /home/abuild/rpmbuild/BUILD/PythonQt3.2/src/PythonQtConversion.h:384: undefined reference to `PySequence_GetItem'
[  291s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /tmp/libPythonQt-Qt5-Python3.so.3.2.0.HHrIKK.ltrans2.ltrans.o: in function `bool PythonQtConvertPythonToPair<double, double>(_object*, void*, int, bool)':
[  291s] /usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
[  291s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /tmp/libPythonQt-Qt5-Python3.so.3.2.0.HHrIKK.ltrans2.ltrans.o: in function `bool PythonQtConvertPythonToPair<QString, QString>(_object*, void*, int, bool)':
[  291s] /home/abuild/rpmbuild/BUILD/PythonQt3.2/src/PythonQtConversion.h:368: undefined reference to `PySequence_Check'
[  291s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/PythonQt3.2/src/PythonQtConversion.h:369: undefined reference to `PySequence_Size'
[  291s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/PythonQt3.2/src/PythonQtConversion.h:374: undefined reference to `PySequence_GetItem'
[  291s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /tmp/libPythonQt-Qt5-Python3.so.3.2.0.HHrIKK.ltrans2.ltrans.o: in function `bool PythonQtConvertPythonToPair<QString, QString>(_object*, void*, int, bool)':
[  291s] /usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
```

**Comment by krop** [comment]
Here's the reason: With python 3.8, python3-config --libs doesn't contain -lpython3.8.
For that you need to use python3-config --embed --libs

```
# python3-config --libs
 -lcrypt -lpthread -ldl  -lutil -lm -lm

# python3-config --embed --libs
-lpython3.8 -lcrypt -lpthread -ldl  -lutil -lm -lm

```

**Comment by he-hesce** [comment]
--embed is not supported by python2.7-config so the calls to python2.7-config fails. Is it possible to check so that --embed is only used if it is supported, i.e., on Python 3.x? I don't know which 3.x version introduced --embed.

**Comment by he-hesce** [comment]
I created Issue #35.
