### ISSUE TITLE
Potential null pointer dereference in PythonQtConvertListOfKnownClassToPythonList

### ISSUE THREAD

**Issue by samoptibrium** [MeVisLab/pythonqt#60]
https://github.com/MeVisLab/pythonqt/blob/58ccd5393922d88fd320628aa2db787df1f1233b/src/PythonQtConversion.h#L272-L275

https://github.com/MeVisLab/pythonqt/blob/58ccd5393922d88fd320628aa2db787df1f1233b/src/PythonQtConversion.h#L292-L295

This code checks the "innerType" pointer for null and then, if null, is dereferencing the pointer in the cerr prints.

**Comment by usiems** [comment]
Indeed, QMetaType::typeName(metaTypeId) should be used instead of innerType->className().constData(), like in the methods above.
I guess this never was a problem because these methods really are only used with known classes.
