### ISSUE TITLE
i use pythonqt in a new envirment ,if i must instll python.exe

### ISSUE THREAD

**Issue by YuDe95** [MeVisLab/pythonqt#62]
### environment
python3.7.9
qt 5.13
win10
### issue
when i release my app i can't run my app.so i delete my code .when i delete
```
    PythonQt::init(PythonQt::IgnoreSiteModule | PythonQt::RedirectStdOut);
    PythonQt::init();
    PythonQt_QtAll::init();
    PythonQtObjectPtr  mainContext = PythonQt::self()->getMainModule();
    PythonQtScriptingConsole *console = new PythonQtScriptingConsole(this, mainContext);
    m_topSplitter->addWidget(console);
    m_topSplitter->setStretchFactor(0,50);
    m_topSplitter->setStretchFactor(1,2);
```
my app can run .
so i think it maybe issue about it .

### solution

so i think it maybe python cause this.so i intall python3.7.9. and surprise it can run successfully. but i want to kown if i must install python.or it have other solution.

**Comment by mrbean-bremen** [comment]
PythonQt is a Python wrapper for Qt. If you don't bring your own Python with your application (like MeVisLab does), you need an installed Python.
