### ISSUE TITLE
Potential memory leack in pythonQTPrivate object

### ISSUE THREAD

**Issue by BenoitKrafft** [MeVisLab/pythonqt#70]
Hello,
I have been using PythonQT and i had to read the code to understand what's happening.
I think I may have found a memory leack in PythonQTPrivate.
PythonQtPrivate::PythonQtPrivate()
{
  _importInterface = NULL;
  _defaultImporter = new PythonQtQFileImporter;
  _noLongerWrappedCB = NULL;
  _wrappedCB = NULL;
  _qObjectMissingAttribCB = NULL;
  _currentClassInfoForClassWrapperCreation = NULL;
  _profilingCB = NULL;
  _hadError = false;
  _systemExitExceptionHandlerEnabled = false;
  _debugAPI = new PythonQtDebugAPI(this);
}

PythonQtPrivate::~PythonQtPrivate() {
  delete _defaultImporter;
  _defaultImporter = NULL;

//missing delete _debugAPI ??
  _**delete _debugAPI;
  _debugAPI = NULL;**_

  qDeleteAll(_knownClassInfos);

  PythonQtMethodInfo::cleanupCachedMethodInfos();
  PythonQtArgumentFrame::cleanupFreeList();
}
I think delete _debugAPI is missing since we got a new in the constructor.
Tell me if I am wrong, if i missed somethink, a mecanism deleting it somehow.
If so, maybe add a comment to say so?
Thanks

**Comment by florianlink** [comment]
_debugAPI = new PythonQtDebugAPI(this);

Since the object is a QObject and the parent is PythonQt, it is deleted by
Qt.
