### ISSUE TITLE
Overriding method itemChange() not possible in Python for QAbstractGraphicsShapeItem derived classes

### ISSUE THREAD

**Issue by mbarann** [MeVisLab/pythonqt#75]
Overriding method itemChange() ist not possible in Python for QAbstractGraphicsShapeItem derived classes, e.g. when sub classing QGraphicsRectItem.

This is caused by not including the itemChange() method in the generated code of class PythonQtShell_QGraphicsRectItem:
https://github.com/MeVisLab/pythonqt/blob/master/generated_cpp_511/com_trolltech_qt_gui/com_trolltech_qt_gui3.h#L457

Class PythonQtShell_QGraphicsPixmapItem, which does not derive from QAbstractGraphicsShapeItem, contains this method:
https://github.com/MeVisLab/pythonqt/blob/master/generated_cpp_511/com_trolltech_qt_gui/com_trolltech_qt_gui3.h#L110

After debugging the code generator, I found that the traversal of the base class hierarchy ignores the interface classes from which any super class inherits:
https://github.com/MeVisLab/pythonqt/blob/master/generator/abstractmetalang.cpp#L1632

**Comment by mbarann** [comment]
Here is a proposed patch to fix the code generation: [patch.txt](https://github.com/MeVisLab/pythonqt/files/9869537/patch.txt)

**Comment by usiems** [comment]
I applied a fix that should consider really any interface class (in this context the secondary classes in multiple inheritance) in the inheritance chain.

**Comment by mbarann** [comment]
> I applied a fix that should consider really any interface class (in this context the secondary classes in multiple inheritance) in the inheritance chain.

I had the same thought too. Additionally, I would also call `super_class->fixFunctions()` after `super_class = super_class->baseClass()` when traversing the hierarchy.

**Comment by florianlink** [comment]
I don’t think that would be necessary, fixFunctions is already called on
all classes in a loop.

**Comment by mbarann** [comment]
> I don’t think that would be necessary, fixFunctions is already called on
all classes in a loop.
I think it depends on the iteration order in the loop. If `fixFunctions()` is called on a `derived_class` before it is called on its base classes, then `derived_class->fixFunctions()` will iterate over the class hierarchy where all but the direct base class have not initialized there functions yet.

**Comment by usiems** [comment]
Yeah, and the call to fix_functions calls fix_functions for the super_class recursively. Everything is as it should be.

**Comment by mbarann** [comment]
Right, I missed the recursive nature there.
