### ISSUE TITLE
MacOS 13.0.1 occured Error when building this code

### ISSUE THREAD

**Issue by Wangyao1997-sdu** [MeVisLab/pythonqt#78]
It throw following errors when I make all:

clang: error: no such file or directory: '/Users/wangyao/opt/anaconda3/lib/libQt5Xml_debug.dylib'
clang: error: no such file or directory: '/Users/wangyao/opt/anaconda3/lib/libQt5Core_debug.dylib'

A request for help. Thank you very much

**Comment by mrbean-bremen** [comment]
You need to have the Qt development version installed if you want to build PythonQt.

**Comment by mrbean-bremen** [comment]
Closing as outdated and missing information.
